DROP TABLE if exists autopayment_aut;

DROP INDEX IF EXISTS can_ID;
DROP INDEX IF EXISTS cfg_id;
DROP INDEX IF EXISTS di_ID;
DROP INDEX IF EXISTS fun_ID;
DROP INDEX IF EXISTS fam_ID;
DROP INDEX IF EXISTS fr_ID;
DROP INDEX IF EXISTS grp_ID_2;
DROP INDEX IF EXISTS grp_ID;
DROP INDEX IF EXISTS mb_ID;
DROP INDEX IF EXISTS pn_ID;
DROP INDEX IF EXISTS per_ID;
DROP INDEX IF EXISTS p2vo_ID;
DROP INDEX IF EXISTS pro_ID_2;
DROP INDEX IF EXISTS pro_ID;
DROP INDEX IF EXISTS prt_ID_2;
DROP INDEX IF EXISTS prt_ID;
DROP INDEX IF EXISTS qry_ID_2;
DROP INDEX IF EXISTS qry_ID;
DROP INDEX IF EXISTS qpo_ID;
DROP INDEX IF EXISTS qrp_ID_2;
DROP INDEX IF EXISTS qrp_ID;
DROP INDEX IF EXISTS usr_per_ID;
DROP INDEX IF EXISTS vol_ID;
DROP INDEX IF EXISTS kdev_ID;

/**
  Missing auto increment for the table
 */
-- SQLite does not support CHANGE COLUMN; assume location_id already integer primary key.
